GPUS: 0
WORKERS: 4

DATASET:
  IMAGE_SIZE: 64
  ROOT: 'dataset/data/${DATASET.NAME}'
  NUM_WORKERS: 3

TRAIN:
  NUM_MODEL: 3
  BATCH_SIZE: 64
  EPOCHS: 250
  MULTIPLIER: 1
  LATENT_SIZE: 16
  LAYERS: 4
  OUT_CHANNELS_PRE: 512
  LR: 1e-4
  WEIGHT_DECAY: 0
  SEED: 9
  LAMBDA: 1
  PRETRAINED: False
  RESUME: False

TEST:
  BATCH_SIZE: 1

OUTPUT:
  DIRECTORY: 'output'
  LOGS_TRAIN: '${OUTPUT.DIRECTORY}/logs/${DATASET.NAME}_train_logs'
  LOGS_TEST: '${OUTPUT.DIRECTORY}/logs/${DATASET.NAME}_test_logs'
  CHECKPOINT: '${OUTPUT.DIRECTORY}/checkpoint/${DATASET.NAME}/${TRAIN.MODEL_NAME}'
  BEST: '${OUTPUT.DIRECTORY}/best/${DATASET.NAME}/${TRAIN.MODEL_NAME}'

MODEL:
  PRETRAINED: 'pretrained'
